### ISSUE TITLE
Reusing DialogServiceConnector and InputAudioStream for Multiple Utterances

### ISSUE THREAD

**Issue by achaloyan** [Azure-Samples/Cognitive-Services-Voice-Assistant#306]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> My goal is to use the same instance of DialogServiceConnector for multiple utterances in the scope of a single dialog. The use is very similar to the sample cpp-console application. Though, instead of microphone, an input audio stream must be used.

> Although everything works as intended with the sample application, I am getting quite unexpected results by implementing either PushInputStream or PullInputStream approaches. First recognition attempt always completes normally. However, the next one fails. Interestingly enough, it looks like every next attempt succeeds. 

> For demonstration purposes, I have made minimal changes on top of the sample cpp-console application for both PushInputStream and PullInputStream. In order to reproduce the problem, you may use the corresponding patches in the attached archive file.

### Any log messages given by the failure
> The attached archive file contains logs collected as a a result of each test case.

[cpp-console-app-data.zip](https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/files/4571935/cpp-console-app-data.zip)

### Expected/desired behavior
> Recognition should work for first and all the consecutive attempts using the same instance of DialogServiceConnector and an associated audio input stream.

### OS and Version?
> Windows 10

### Versions
>VS 2017 x64, Speech SDK 1.10.0

### Mention any other details that might be useful
I suspect the internal audio buffer is not reset upon invocation of ListenOnceAsync(). There does not seem any API method available for the user application to reset the buffer implicitly before calling ListenOnceAsync(). 

Please take a look and let me know if you need anything in addition.

Thanks
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dargilco** [comment]
Hi @achaloyan, thank you for your detailed description. You are absolutely right that managing multi-turn dialog with an input stream is tricky. Input streams were originally designed for one-shot speech recognition scenarios, and multi-turn dialogs was a relatively recent addition. We are reviewing options for improving the SDK APIs to better manage input streams in multi-turn scenarios.
We do have a couple of C# samples that use input stream to manage multi turn successfully. One is the [Voice Assistant Test tool](https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/tree/master/clients/csharp-dotnet-core/voice-assistant-test). The other is the [UWP Voice Assistant sample](https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/tree/master/clients/csharp-uwp). I suggest you have a look at the test tool, as the UWP sample is more complex. 
You should be able to get it to work in C++ with these guidelines: 
* Please use [PushAudioInputStream](https://docs.microsoft.com/en-us/cpp/cognitive-services/speech/audio-pushaudioinputstream)
* As you've noticed, there is no way currently to reset the internal audio buffer between dialog turns. And if you try to delete the PushAudioInputStream and create a new one between turns, you will be forced to reestablish the connection to Direct Line Speech. So you have to use a single active PushAudioInputStream for all turns in the dialog. 
  * You need to make sure you stop writing audio data to the stream as soon as you get the speech recognition result ("RecognizedSpeech" event). Resume writing audio data to the stream right before calling ListenOnceAsync().
  * Make sure there are only short period of silence written into the input stream between turns. If there a few seconds of silence, and it's fed into the recognizer at the begging of the 2nd turn (for example), the speech recognition engine will produce a "NoMatch" event indicating it stopped due to the silence. Even though you continued to write audio with speech following the silence in to the stream.

I am interested to hear about the application you are building, so we can better help you. I'll reach out to you privately. 

Thanks,
Darren

**Comment by achaloyan** [comment]
Hi Darren,

Thank you for your response. By following your guidelines, I've been able to circumvent the problem by changing a few lines of code in my version of the sample cpp-console application using PushAudioInputStream. Please find below a few important details/thoughts I would like to share and possibly get your feedback.

Now, I start writing audio before calling ListenOnceAsync() by temporarily using Sleep(100), which is sufficient for the sample application. Of course, a real-world application can makes sure one or two frames are written and only then call ListenOnceAsync() without using any sleeps. However, in my understanding, there is still no guarantee this approach would work reliably under even moderate load, given the asynchronous processing and thread context switching.

The second change that I had to make in order to circumvent the problem is to disable signaling of audio stream completion from the user application, which is done by calling pushStream->Write(nullptr, 0).

So, by disabling the above, all the consecutive requests return the expected result. However, there is still a strange sequence of events happening. The SESSION STOPPED event is raised only after the first audio frame is written in the scope of a consecutive request. I do not think this would be the intended behavior, but again, the application can possibly take care of that too. What worries me more is the inability of the user application to signal audio input completion. This is quite important mostly because of response times. 

I am providing a new set of data collected from two attempts with and without signaling completion of audio input by the user application.
[cpp-console-app-data-r2.zip](https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/files/4589716/cpp-console-app-data-r2.zip)

Please take a look and compare the timings in the output results. 

Thanks

**Comment by dargilco** [comment]
You are right about making sure you do NOT call Write(nullptr, 0), while in the middle of a multi-turn conversation, as this will close the stream and thus invalidate the client connection to Direct Line Speech. I undestand that limits your ability to signal the end of of audio for a particular turn. We will incorporate this feedback in the design of the updated APIs.

I opened a GitHub issue on me to document how to use input streams with DialogServiceConnector and I'll take care of it in the next couple of weeks.  I'll update this thread with a link when I have it. Your feedback will be welcomed.

With regards to these two issues;
* Relative timing of starting to write audio to the stream and calling listenOnceAsync(), and
* "Session stopped" event being raised,
I will pass that information and logs to the platform teams. I will make sure thier feedback is incorporated in the new document I will write.

Darren
