### ISSUE TITLE
"take away three green boxes" results in adding instread of reducing number of boxes

### ISSUE THREAD

**Issue by dargilco** [Azure-Samples/Cognitive-Services-Voice-Assistant#412]
Install the Inventory CC demo

Say "take away three green boxes"

The agent will reply "3 green boxes have been added"

It should reduce the number of boxes, not add

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by JPalmerDev** [comment]
This is fixed by updating the Query sample utterances to include a few new entries.
The first bold group is necessary.

What do we have in stock?
What's the stock look like?
What's in stock?
What's in the warehouse?
What do we have?
Take stock
Query
Query inventory
Query the warehouse
Take stock of whats in the warehouse
How many {WhichItem} are in stock?
**How many {WhichItem} in the inventory**
How many {WhichItem} do we have
Query {WhichItem}
Count {WhichItem}
**{WhichItem} query
{WhichItem} count**
What's the count of {WhichItem}
Tell me how many {WhichItem} we have?

**Comment by JPalmerDev** [comment]
This should solve these issues.

**Receive Sample sentences**:
add
add {WhichItem}
add a {WhichItem}
add {Quantity} {WhichItem}
receive
receive {WhichItem}
receive a {WhichItem}
receive {Quantity} {WhichItem}
take in
take in {WhichItem}
take in {Quantity} {WhichItem}
make
make a {WhichItem}
make {Quantity} {WhichItem}
I made
I made {WhichItem}
I made a {WhichItem}
I made {Quantity} {WhichItem}
store
store {WhichItem}
store a {WhichItem}
store {Quantity} {WhichItem}
order
order {WhichItem}
order a {WhichItem}
order {Quantity} {WhichItem}

**Ship sample sentences**
delete
delete {WhichItem}
delete {Quantity} {WhichItem}
cross out
cross out {WhichItem}
cross out {Quantity} {WhichItem}
sell
sell {WhichItem}
sell {Quantity} {WhichItem}
reduce
reduce {WhichItem}
reduce {Quantity} {WhichItem}
Remove
Remove {WhichItem}
Remove {Quantity} {WhichItem}
Ship
Ship {WhichItem}
Ship {Quantity} {WhichItem}
take away
take away {WhichItem}
take away {Quantity} {WhichItem}
take out
take out {WhichItem}
take out {Quantity} {WhichItem}

**Comment by JPalmerDev** [comment]
I have provided Fan with a manually updated json that fixes these queries.
