### ISSUE TITLE
Task.Run(...).Wait()

### ISSUE THREAD

**Issue by hraz-msft** [Azure-Samples/Cognitive-Services-Voice-Assistant#483]
https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/blob/bae28b5389a949a71759ac71229fa7e2c3b54b35/clients/csharp-wpf/VoiceAssistantClient/MainWindow.xaml.cs#L398

What is the motivation to do `Task.Run(...).Wait()` here?

**Comment by splumber** [comment]
Hi @hraz-msft, thank you for bringing this to our attention. You are correct, the Task.Run(...).Wait() is redundant and not needed. Currently we are downloading the entire TTS before playback; a better design would be to play TTS as it is received.

**Comment by hraz-msft** [comment]
Do you have any plans to improve it? I want to learn from your code the best practices for using DLS

**Comment by dargilco** [comment]
Hi @hraz-msft, @splumber opened a new issue #484 "Play TTS as it is received instead of downloading it first". Unfortunately, we won't be able to get to it right now. If you have an implementation and want to contribute to this GitHub repo, feel free to fork the repo and create a PR for us to review. I'm closing this issue since #484 will be tracking this. Thanks, Darren.
