### ISSUE TITLE
C++ client timestamp is UTC

### ISSUE THREAD

**Issue by wellsi** [Azure-Samples/Cognitive-Services-Voice-Assistant#502]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Using the C++ client, try a recognition event, look at the console output

### Any log messages given by the failure
>
New status : Detecting
SESSION STARTED: 699c4de5-764c-483f-af22-68414e730f25 ...
16:24:47.864  ActivityReceived, type=event, audio=false
INTERMEDIATE: computer ...

### Expected/desired behavior
> The above output occurred at 9:24am PST
As output that the customer sees, it is hard to work out the localtime <-> UTC

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dargilco** [comment]
Thanks @wellsi ! I'll fix this in the internal C++ code I'm working on and port the fix to this public sample.

**Comment by dargilco** [comment]
@wellsi this works fine for me when running on Windows, because it reads the time zone from Windows. To fix this on your Linux device my guess would be you need to set the time zone before running the code. I found [this random page](https://linuxize.com/post/how-to-set-or-change-timezone-in-linux/) on setting time zone on Linux. Let me know if that helped and what you did so we can update the instructions to include setting time zone.

**Comment by wellsi** [comment]
Thanks - so it was user error. The RPi defaulted to UTC. Once the TZ was setup correctly, the right result was displayed.
